In [54]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.svm import OneClassSVM
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    precision_score,
    recall_score,
    f1_score
)

import optuna

In [2]:
data_path = '../src/features.csv'

In [3]:
df = pd.read_csv(data_path, index_col=0)
df.head()

,record_id,r_peak,annotation_sample,type,dist_from_annotation,anomaly,mean,std,min,max,...,median,iqr,energy,rms,skew,kurtosis,max_abs,mean_abs,waveform_length,max_diff
0,100,370,370.0,N,0.0,0,-0.317893,0.190568,-0.535,0.940,...,-0.3350,0.095,38.464150,0.370637,4.708594,24.842114,0.940,0.357714,5.350,0.325
1,100,663,662.0,N,1.0,0,-0.334286,0.173790,-0.570,0.960,...,-0.3575,0.085,39.745950,0.376762,5.330684,32.266664,0.960,0.366321,5.375,0.470
2,100,947,946.0,N,1.0,0,-0.331839,0.164789,-0.645,0.860,...,-0.3600,0.085,38.436375,0.370503,5.014945,30.068983,0.860,0.360946,5.315,0.410
3,100,1231,1231.0,N,0.0,0,-0.337000,0.155884,-0.565,0.820,...,-0.3550,0.090,38.603250,0.371307,5.159448,31.413284,0.820,0.363036,5.240,0.390
4,100,1515,1515.0,N,0.0,0,-0.325554,0.166004,-0.545,0.885,...,-0.3400,0.110,37.391925,0.365435,4.924310,29.010657,0.885,0.354696,5.225,0.390

In [5]:
id_columns = [
    'record_id',
    'r_peak',
    'annotation_sample',
    'type',
    'dist_from_annotation',
    'anomaly'
]

feature_columns = [
    col for col in df.columns
    if col not in id_columns
]

In [7]:
print(feature_columns)

['mean', 'std', 'min', 'max', 'peak_to_peak', 'median', 'iqr', 'energy', 'rms', 'skew', 'kurtosis', 'max_abs', 'mean_abs', 'waveform_length', 'max_diff']

In [49]:
record_ids = df['record_id'].unique()

train_ids, temp_ids = train_test_split(
    record_ids,
    test_size=0.4,
    random_state=42
)

val_ids, test_ids = train_test_split(
    temp_ids,
    test_size=0.5,
    random_state=42
)

print("Train:", len(train_ids))
print("Validation:", len(val_ids))
print("Test:", len(test_ids))

Train: 27
Validation: 9
Test: 10

In [50]:
train_df_all = df[
    df['record_id'].isin(train_ids)
].copy()

train_df = train_df_all[
    train_df_all['anomaly'] == 0
].copy()

val_df = df[
    df['record_id'].isin(val_ids)
].copy()

test_df = df[
    df['record_id'].isin(test_ids)
].copy()

In [51]:
train_df['anomaly'].value_counts()

anomaly
0    44556
Name: count, dtype: int64

In [53]:
val_df['anomaly'].value_counts()

anomaly
0    13751
1     2915
Name: count, dtype: int64

In [52]:
test_df['anomaly'].value_counts()

anomaly
0    14988
1     7040
Name: count, dtype: int64

In [55]:
X_train = train_df[feature_columns]

X_val = val_df[feature_columns]
y_val = val_df['anomaly']

X_test = test_df[feature_columns]
y_test = test_df['anomaly']

In [56]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_val_scaled = scaler.transform(X_val)

X_test_scaled = scaler.transform(X_test)

In [62]:
def objective(trial):
    nu = trial.suggest_float('nu', 0.001, 0.2, log=True)
    gamma = trial.suggest_float('gamma', 1e-4, 1.0, log=True)
    kernel = trial.suggest_categorical('kernel', ['rbf', 'poly', 'sigmoid'])
    tol = trial.suggest_float('tol', 1e-5, 1e-2, log=True)
    
    params = {
        'kernel': kernel,
        'nu': nu,
        'gamma': gamma,
        'tol': tol
    }
    
    if kernel == 'poly':
        params['degree'] = trial.suggest_int('degree', 2, 5)
        params['coef0'] = trial.suggest_float('coef0', -1, 1)
    
    elif kernel == 'sigmoid':
        params['coef0'] = trial.suggest_float('coef0', -1, 1)
        
    model = OneClassSVM(**params)
    model.fit(X_train_scaled)
    
    pred = model.predict(X_val_scaled)
    y_pred = np.where(
        pred == -1,
        1,
        0
    )
    
    precision = precision_score(y_val, y_pred, zero_division=0)
    recall = recall_score(y_val, y_pred, zero_division=0)
    f1 = f1_score(y_val, y_pred, zero_division=0)
    
    trial.set_user_attr('precision', precision)
    trial.set_user_attr('recall', recall)
    
    return f1

In [60]:
study = optuna.create_study(
    direction='maximize'
)

[I 2026-08-29 15:34:18,540] A new study created in memory with name: no-name-421b5482-16b0-4ba9-96e0-8bb0938d720a

In [63]:
study.optimize(
    objective,
    n_trials=30
)

[I 2026-08-29 15:34:39,397] Trial 1 finished with value: 0.07542318405828155 and parameters: {'nu': 0.034827781005028806, 'gamma': 0.0023205458170060178, 'kernel': 'sigmoid', 'tol': 0.0004830590141609036, 'coef0': -0.28617775205882023}. Best is trial 1 with value: 0.07542318405828155.
[I 2026-08-29 15:34:41,870] Trial 2 finished with value: 0.05370414768640614 and parameters: {'nu': 0.019355348018422383, 'gamma': 0.005588823071718204, 'kernel': 'sigmoid', 'tol': 7.491020092928468e-05, 'coef0': -0.8938469638061113}. Best is trial 1 with value: 0.07542318405828155.
[I 2026-08-29 15:35:15,620] Trial 3 finished with value: 0.1376464763162238 and parameters: {'nu': 0.19156500133497809, 'gamma': 0.002194231369689969, 'kernel': 'sigmoid', 'tol': 0.0012551326568590643, 'coef0': -0.016398275606032797}. Best is trial 3 with value: 0.1376464763162238.
[I 2026-08-29 15:35:17,584] Trial 4 finished with value: 0.2209737827715356 and parameters: {'nu': 0.0014611604471920859, 'gamma': 0.23060087756527997, 'kernel': 'rbf', 'tol': 0.00010904409874373473}. Best is trial 4 with value: 0.2209737827715356.
[I 2026-08-29 15:35:19,297] Trial 5 finished with value: 0.24673029338989041 and parameters: {'nu': 0.001741365661482868, 'gamma': 0.26857687377274403, 'kernel': 'rbf', 'tol': 1.6425033034230295e-05}. Best is trial 5 with value: 0.24673029338989041.
[I 2026-08-29 15:35:19,484] Trial 6 finished with value: 0.004066418163334463 and parameters: {'nu': 0.0013212886398216118, 'gamma': 0.00018078132601206395, 'kernel': 'sigmoid', 'tol': 0.00013833871379001332, 'coef0': 0.6160906952524037}. Best is trial 5 with value: 0.24673029338989041.
[I 2026-08-29 15:35:20,788] Trial 7 finished with value: 0.10665897953300663 and parameters: {'nu': 0.014508421339592896, 'gamma': 0.004626881470761855, 'kernel': 'sigmoid', 'tol': 0.00975469966907338, 'coef0': 0.1319857505718527}. Best is trial 5 with value: 0.24673029338989041.
[I 2026-08-29 15:35:22,809] Trial 8 finished with value: 0.0 and parameters: {'nu': 0.014570972267385579, 'gamma': 0.16045475746476298, 'kernel': 'sigmoid', 'tol': 0.00015367447064329205, 'coef0': 0.29047778005529223}. Best is trial 5 with value: 0.24673029338989041.
[I 2026-08-29 15:35:36,014] Trial 9 finished with value: 0.12627986348122866 and parameters: {'nu': 0.10665168716227552, 'gamma': 0.003131673228271475, 'kernel': 'sigmoid', 'tol': 0.00022749693660816623, 'coef0': 0.2577865518635565}. Best is trial 5 with value: 0.24673029338989041.
[I 2026-08-29 15:35:41,186] Trial 10 finished with value: 0.33496697208608567 and parameters: {'nu': 0.006412933472684662, 'gamma': 0.6855287502382857, 'kernel': 'rbf', 'tol': 6.130330501476523e-05}. Best is trial 10 with value: 0.33496697208608567.
[I 2026-08-29 15:35:41,588] Trial 11 finished with value: 0.04007902907140841 and parameters: {'nu': 0.004458096848955842, 'gamma': 0.03396061967015125, 'kernel': 'poly', 'tol': 1.03848624189668e-05, 'degree': 4, 'coef0': 0.9716156574683407}. Best is trial 10 with value: 0.33496697208608567.
[I 2026-08-29 15:35:48,165] Trial 12 finished with value: 0.3373638853630837 and parameters: {'nu': 0.00393922172637342, 'gamma': 0.8430818039840811, 'kernel': 'rbf', 'tol': 1.5509146793172178e-05}. Best is trial 12 with value: 0.3373638853630837.
[I 2026-08-29 15:35:59,030] Trial 13 finished with value: 0.33708330457588515 and parameters: {'nu': 0.004822671235787212, 'gamma': 0.7456902331755841, 'kernel': 'rbf', 'tol': 3.144857838225854e-05}. Best is trial 12 with value: 0.3373638853630837.
[I 2026-08-29 15:36:13,462] Trial 14 finished with value: 0.3372962864012824 and parameters: {'nu': 0.004132535003991871, 'gamma': 0.8446210407589032, 'kernel': 'rbf', 'tol': 2.7319974022318293e-05}. Best is trial 12 with value: 0.3373638853630837.
[I 2026-08-29 15:36:14,200] Trial 15 finished with value: 0.14162112932604737 and parameters: {'nu': 0.003268651202376283, 'gamma': 0.04418621266042212, 'kernel': 'rbf', 'tol': 2.943745046434994e-05}. Best is trial 12 with value: 0.3373638853630837.
[I 2026-08-29 15:36:15,216] Trial 16 finished with value: 0.002029083530605343 and parameters: {'nu': 0.00813857414401119, 'gamma': 0.9712853565999148, 'kernel': 'poly', 'tol': 2.5322205827809812e-05, 'degree': 2, 'coef0': -0.755175276611879}. Best is trial 12 with value: 0.3373638853630837.
[I 2026-08-29 15:36:15,978] Trial 17 finished with value: 0.1749795584627964 and parameters: {'nu': 0.002441784778466518, 'gamma': 0.07357661665092934, 'kernel': 'rbf', 'tol': 1.0520706225695634e-05}. Best is trial 12 with value: 0.3373638853630837.
[I 2026-08-29 15:36:18,999] Trial 18 finished with value: 0.3037893384714194 and parameters: {'nu': 0.008022352571184018, 'gamma': 0.3303474684045844, 'kernel': 'rbf', 'tol': 0.0003722167159910167}. Best is trial 12 with value: 0.3373638853630837.
[I 2026-08-29 15:36:30,932] Trial 19 finished with value: 0.17597715509548456 and parameters: {'nu': 0.05231428369754379, 'gamma': 0.01819016432810461, 'kernel': 'rbf', 'tol': 4.877777519356909e-05}. Best is trial 12 with value: 0.3373638853630837.
[I 2026-08-29 15:36:31,114] Trial 20 finished with value: 0.004776526782668032 and parameters: {'nu': 0.0010517439150134523, 'gamma': 0.09469157989415962, 'kernel': 'poly', 'tol': 0.002928557132189605, 'degree': 5, 'coef0': -0.3218419361663854}. Best is trial 12 with value: 0.3373638853630837.
[I 2026-08-29 15:36:35,978] Trial 21 finished with value: 0.346921224630203 and parameters: {'nu': 0.0025305705646273807, 'gamma': 0.4471061034959143, 'kernel': 'rbf', 'tol': 1.9603085767061163e-05}. Best is trial 21 with value: 0.346921224630203.
[I 2026-08-29 15:36:39,213] Trial 22 finished with value: 0.3473030655801319 and parameters: {'nu': 0.0030418245418878443, 'gamma': 0.3841686384384014, 'kernel': 'rbf', 'tol': 2.114484674938115e-05}. Best is trial 22 with value: 0.3473030655801319.
[I 2026-08-29 15:36:43,958] Trial 23 finished with value: 0.3494132985658409 and parameters: {'nu': 0.002359143674532908, 'gamma': 0.44155459078179077, 'kernel': 'rbf', 'tol': 1.68419794721345e-05}. Best is trial 23 with value: 0.3494132985658409.
[I 2026-08-29 15:36:46,829] Trial 24 finished with value: 0.31773757537949676 and parameters: {'nu': 0.0021001826584715047, 'gamma': 0.3464114336481093, 'kernel': 'rbf', 'tol': 4.185483134363994e-05}. Best is trial 23 with value: 0.3494132985658409.
[I 2026-08-29 15:36:47,948] Trial 25 finished with value: 0.198415432311402 and parameters: {'nu': 0.0026337939082225876, 'gamma': 0.11522640938730176, 'kernel': 'rbf', 'tol': 2.0048974165157028e-05}. Best is trial 23 with value: 0.3494132985658409.
[I 2026-08-29 15:36:51,193] Trial 26 finished with value: 0.3487633529015494 and parameters: {'nu': 0.001002946131356107, 'gamma': 0.3898844579844218, 'kernel': 'rbf', 'tol': 7.380637648172407e-05}. Best is trial 23 with value: 0.3494132985658409.
[I 2026-08-29 15:36:51,634] Trial 27 finished with value: 0.012607830126078301 and parameters: {'nu': 0.0010358123612447382, 'gamma': 0.013568882063694035, 'kernel': 'poly', 'tol': 8.448341312117248e-05, 'degree': 2, 'coef0': 0.9732731690523407}. Best is trial 23 with value: 0.3494132985658409.
[I 2026-08-29 15:36:52,999] Trial 28 finished with value: 0.20457488131204143 and parameters: {'nu': 0.0015363360277651692, 'gamma': 0.15853922005727022, 'kernel': 'rbf', 'tol': 5.6243494738338164e-05}. Best is trial 23 with value: 0.3494132985658409.
[I 2026-08-29 15:36:53,344] Trial 29 finished with value: 0.019499512512187196 and parameters: {'nu': 0.0018413647498711242, 'gamma': 0.0003791901072272697, 'kernel': 'rbf', 'tol': 0.00024586040511387857}. Best is trial 23 with value: 0.3494132985658409.
[I 2026-08-29 15:36:54,506] Trial 30 finished with value: 0.15161229492739958 and parameters: {'nu': 0.005907050328098756, 'gamma': 0.054205863970168175, 'kernel': 'rbf', 'tol': 4.345918781640436e-05}. Best is trial 23 with value: 0.3494132985658409.

In [64]:
best_trial = study.best_trial

print("F1:", best_trial.value)
print("Precision:", best_trial.user_attrs['precision'])
print("Recall:", best_trial.user_attrs['recall'])
print("Params:", best_trial.params)

F1: 0.3494132985658409
Precision: 0.2339930151338766
Recall: 0.6895368782161235
Params: {'nu': 0.002359143674532908, 'gamma': 0.44155459078179077, 'kernel': 'rbf', 'tol': 1.68419794721345e-05}

In [66]:
best_model = OneClassSVM(**best_trial.params)
best_model.fit(X_train_scaled)

OneClassSVM(gamma=0.44155459078179077, nu=0.002359143674532908,
            tol=1.68419794721345e-05)

In [67]:
val_pred = best_model.predict(X_val_scaled)
y_val_pred = np.where(val_pred == -1, 1, 0)

cm = confusion_matrix(y_val, y_val_pred)

print(cm)

[[7171 6580]
 [ 905 2010]]

In [68]:
val_results = val_df.copy()

val_results['prediction'] = y_val_pred

In [69]:
pd.crosstab(
    val_results['type'],
    val_results['prediction'],
    normalize='index'
)

prediction         0         1
type
A           0.230769  0.769231
E           0.009901  0.990099
F           0.000000  1.000000
L           0.348236  0.651764
N           0.521489  0.478511
R           0.941176  0.058824
V           0.171184  0.828816

In [70]:
type_results = val_results.groupby('type').agg(
    count=('type', 'size'),
    detected=('prediction', 'sum')
)

type_results['detection_rate'] = (
    type_results['detected']
    / type_results['count']
)

type_results

      count  detected  detection_rate
type
A        13        10        0.769231
E       101       100        0.990099
F         2         2        1.000000
L      2013      1312        0.651764
N     13751      6580        0.478511
R        85         5        0.058824
V       701       581        0.828816

In [71]:
normal_val = val_results[
    val_results['type'] == 'N'
]

false_positive_rate = (
    normal_val['prediction'].mean()
)

print(false_positive_rate)

0.47851065377063484

In [42]:
pred = ocsvm.predict(X_test_scaled)
y_pred = np.where(pred == -1, 1, 0)

In [44]:
confusion_matrix(y_test, y_pred)

array([[14551,  2513],
       [ 2899,   707]])

In [47]:
recall = recall_score(y_test, y_pred)

print("Recall:", recall)

Recall: 0.19606211869107043